app = "django-docker-app"
primary_region = "sjc"

[build]
  image = "ahammedfaisal/django-docker-app:latest"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "django_data"
  destination = "/app/data"